// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace BetTeamsBattle.Frontend.Areas.NotAdmin.Controllers {
    public partial class TeamsController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected TeamsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetTeam() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetTeam);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult BattleTopTeams() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.BattleTopTeams);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public TeamsController Actions { get { return MVC.NotAdmin.Teams; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "notadmin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "teams";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string GetTeam = ("GetTeam").ToLowerInvariant();
            public readonly string TopTeams = ("TopTeams").ToLowerInvariant();
            public readonly string BattleTopTeams = ("BattleTopTeams").ToLowerInvariant();
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _Team = "~/Areas/NotAdmin/Views/Teams/_Team.cshtml";
            public readonly string BattleTopTeams = "~/Areas/NotAdmin/Views/Teams/BattleTopTeams.cshtml";
            public readonly string GetTeam = "~/Areas/NotAdmin/Views/Teams/GetTeam.cshtml";
            public readonly string TopTeams = "~/Areas/NotAdmin/Views/Teams/TopTeams.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_TeamsController: BetTeamsBattle.Frontend.Areas.NotAdmin.Controllers.TeamsController {
        public T4MVC_TeamsController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult GetTeam(long teamId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetTeam);
            callInfo.RouteValueDictionary.Add("teamId", teamId);
            return callInfo;
        }

        public override System.Web.Mvc.PartialViewResult TopTeams() {
            var callInfo = new T4MVC_PartialViewResult(Area, Name, ActionNames.TopTeams);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult BattleTopTeams(long battleId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.BattleTopTeams);
            callInfo.RouteValueDictionary.Add("battleId", battleId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
