//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Bets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BetTeamsBattle.Frontend.Areas.NotAdmin.Localization.Resources.Views.Bets.Bets", typeof(Bets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of money you want to bet.
        /// </summary>
        public static string AmountHelpMessage {
            get {
                return ResourceManager.GetString("AmountHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet finished.
        /// </summary>
        public static string BetFinished {
            get {
                return ResourceManager.GetString("BetFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will see bet details as soon as author chooses its output.
        /// </summary>
        public static string BetIsNotClosed {
            get {
                return ResourceManager.GetString("BetIsNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet is private so you won&apos;t be able to see its details.
        /// </summary>
        public static string BetIsPrivate {
            get {
                return ResourceManager.GetString("BetIsPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet on bookmaker&apos;s site.
        /// </summary>
        public static string BetOnBookmakersSite {
            get {
                return ResourceManager.GetString("BetOnBookmakersSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet should be less than {0}.
        /// </summary>
        public static string BetShouldBeLessThan {
            get {
                return ResourceManager.GetString("BetShouldBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet should be more that zero.
        /// </summary>
        public static string BetShouldBeMoreThanZero {
            get {
                return ResourceManager.GetString("BetShouldBeMoreThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet started.
        /// </summary>
        public static string BetStarted {
            get {
                return ResourceManager.GetString("BetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url on bookmaker&apos;s site.
        /// </summary>
        public static string BookmakerUrl {
            get {
                return ResourceManager.GetString("BookmakerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled by bookmaker.
        /// </summary>
        public static string CanceledByBookmaker {
            get {
                return ResourceManager.GetString("CanceledByBookmaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description should uniquely identify your bet. For example: &quot;Barcelona - Real Madrid, draw&quot;.
        /// </summary>
        public static string DescriptionHelpMessage {
            get {
                return ResourceManager.GetString("DescriptionHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is too long.
        /// </summary>
        public static string DescriptionIsTooLong {
            get {
                return ResourceManager.GetString("DescriptionIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description should not be empty.
        /// </summary>
        public static string DescriptionShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("DescriptionShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to make screenshot.
        /// </summary>
        public static string FailedToMakeScreenshot {
            get {
                return ResourceManager.GetString("FailedToMakeScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usually your bet details become visible to other users right after you have chosen bet outcome. It won&apos;t happen if you mark your bet as private (but even in this case bet details will be visible to moderator who will check your bet for cheating).
        /// </summary>
        public static string IsPrivateHelpMessage {
            get {
                return ResourceManager.GetString("IsPrivateHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join to battle to make bets.
        /// </summary>
        public static string JoinToBattleToMakeBets {
            get {
                return ResourceManager.GetString("JoinToBattleToMakeBets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make bet.
        /// </summary>
        public static string MakeBet {
            get {
                return ResourceManager.GetString("MakeBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make bet on behalf of.
        /// </summary>
        public static string MakeBetOnBehalfOf {
            get {
                return ResourceManager.GetString("MakeBetOnBehalfOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making screenshot.
        /// </summary>
        public static string MakingScreenshot {
            get {
                return ResourceManager.GetString("MakingScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me personally.
        /// </summary>
        public static string MePersonally {
            get {
                return ResourceManager.GetString("MePersonally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My bets.
        /// </summary>
        public static string MyBets {
            get {
                return ResourceManager.GetString("MyBets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odds.
        /// </summary>
        public static string Odds {
            get {
                return ResourceManager.GetString("Odds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odds should correspond to the value on bookmaker&apos;s site.
        /// </summary>
        public static string OddsHelpMessage {
            get {
                return ResourceManager.GetString("OddsHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odds should be greater than 1.
        /// </summary>
        public static string OddsShouldBeGreaterThanOne {
            get {
                return ResourceManager.GetString("OddsShouldBeGreaterThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string OfTeam {
            get {
                return ResourceManager.GetString("OfTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome.
        /// </summary>
        public static string Outcome {
            get {
                return ResourceManager.GetString("Outcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input number (e. g. 123.456).
        /// </summary>
        public static string PleaseInputCorrectFloatingNumber {
            get {
                return ResourceManager.GetString("PleaseInputCorrectFloatingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private bet.
        /// </summary>
        public static string PrivateBet {
            get {
                return ResourceManager.GetString("PrivateBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        public static string Screenshot {
            get {
                return ResourceManager.GetString("Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded.
        /// </summary>
        public static string Succeeded {
            get {
                return ResourceManager.GetString("Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team bets.
        /// </summary>
        public static string TeamBets {
            get {
                return ResourceManager.GetString("TeamBets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team has made no bets.
        /// </summary>
        public static string TeamHasMadeNoBets {
            get {
                return ResourceManager.GetString("TeamHasMadeNoBets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url should lead to bookmaker&apos;s site (e. g. http://bookmaker.org) or ideally to the page where your bet is described (e. g. http://bookmaker.org/tennis/today) .
        /// </summary>
        public static string UrlHelpMessage {
            get {
                return ResourceManager.GetString("UrlHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url is incorrect.
        /// </summary>
        public static string UrlIsIncorrect {
            get {
                return ResourceManager.GetString("UrlIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User bets.
        /// </summary>
        public static string UserBets {
            get {
                return ResourceManager.GetString("UserBets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has made no bets.
        /// </summary>
        public static string UserHasMadeNoBets {
            get {
                return ResourceManager.GetString("UserHasMadeNoBets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made no bets.
        /// </summary>
        public static string YouHaveMadeNoBets {
            get {
                return ResourceManager.GetString("YouHaveMadeNoBets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made no bets in this battle.
        /// </summary>
        public static string YouHaveMadeNoBetsInThisBattle {
            get {
                return ResourceManager.GetString("YouHaveMadeNoBetsInThisBattle", resourceCulture);
            }
        }
    }
}
