// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace BetTeamsBattle.Frontend.Areas.Admin.Controllers {
    public partial class AdminBattlesController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AdminBattlesController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AdminBattlesController Actions { get { return MVC.Admin.AdminBattles; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "adminbattles";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string GetBattles = ("GetBattles").ToLowerInvariant();
            public readonly string CreateBattle = ("CreateBattle").ToLowerInvariant();
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string CreateBattle = "~/Areas/Admin/Views/AdminBattles/CreateBattle.cshtml";
            public readonly string GetBattles = "~/Areas/Admin/Views/AdminBattles/GetBattles.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_AdminBattlesController: BetTeamsBattle.Frontend.Areas.Admin.Controllers.AdminBattlesController {
        public T4MVC_AdminBattlesController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult GetBattles() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetBattles);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CreateBattle() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CreateBattle);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CreateBattle(BetTeamsBattle.Frontend.Areas.Admin.Models.Battles.CreateBattleFormViewModel createBattleForm) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CreateBattle);
            callInfo.RouteValueDictionary.Add("createBattleForm", createBattleForm);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
