// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace BetTeamsBattle.Frontend.Areas.NotAdmin.Controllers {
    public partial class BattleBetsController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected BattleBetsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult MyBets() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.MyBets);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult BattleBetSucceeded() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.BattleBetSucceeded);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult BattleBetFailed() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.BattleBetFailed);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public BattleBetsController Actions { get { return MVC.NotAdmin.BattleBets; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "notadmin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "battlebets";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string MyBets = ("MyBets").ToLowerInvariant();
            public readonly string BattleBetSucceeded = ("BattleBetSucceeded").ToLowerInvariant();
            public readonly string BattleBetFailed = ("BattleBetFailed").ToLowerInvariant();
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string MyBets = "~/Areas/NotAdmin/Views/BattleBets/MyBets.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_BattleBetsController: BetTeamsBattle.Frontend.Areas.NotAdmin.Controllers.BattleBetsController {
        public T4MVC_BattleBetsController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult MyBets(long battleId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.MyBets);
            callInfo.RouteValueDictionary.Add("battleId", battleId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult BattleBetSucceeded(long battleBetId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.BattleBetSucceeded);
            callInfo.RouteValueDictionary.Add("battleBetId", battleBetId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult BattleBetFailed(long battleBetId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.BattleBetFailed);
            callInfo.RouteValueDictionary.Add("battleBetId", battleBetId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
