// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC {
    public class SharedController {

        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _OneOrTwoColumnsLayoutBase = "~/Views/Shared/_OneOrTwoColumnsLayoutBase.cshtml";
            static readonly _Languages s_Languages = new _Languages();
            public _Languages Languages { get { return s_Languages; } }
            public partial class _Languages{
                public readonly string _AllLanguages = "~/Views/Shared/Languages/_AllLanguages.cshtml";
                public readonly string _Language = "~/Views/Shared/Languages/_Language.cshtml";
            }
            static readonly _OneColumn s_OneColumn = new _OneColumn();
            public _OneColumn OneColumn { get { return s_OneColumn; } }
            public partial class _OneColumn{
                public readonly string _OneColumnLayout = "~/Views/Shared/OneColumn/_OneColumnLayout.cshtml";
            }
            static readonly _ThreeColumns s_ThreeColumns = new _ThreeColumns();
            public _ThreeColumns ThreeColumns { get { return s_ThreeColumns; } }
            public partial class _ThreeColumns{
                public readonly string _LeftColumnBlock = "~/Views/Shared/ThreeColumns/_LeftColumnBlock.cshtml";
                public readonly string _RightColumnBlock = "~/Views/Shared/ThreeColumns/_RightColumnBlock.cshtml";
                public readonly string _ThreeColumnsLayout = "~/Views/Shared/ThreeColumns/_ThreeColumnsLayout.cshtml";
            }
            static readonly _TwoColumns s_TwoColumns = new _TwoColumns();
            public _TwoColumns TwoColumns { get { return s_TwoColumns; } }
            public partial class _TwoColumns{
                public readonly string _LeftColumnBlock = "~/Views/Shared/TwoColumns/_LeftColumnBlock.cshtml";
                public readonly string _TwoColumnsLayout = "~/Views/Shared/TwoColumns/_TwoColumnsLayout.cshtml";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
