//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BattleBets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BattleBets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BetTeamsBattle.Frontend.Areas.NotAdmin.Localization.Resources.Views.BattleBets.Ba" +
                            "ttleBets", typeof(BattleBets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet.
        /// </summary>
        public static string Bet {
            get {
                return ResourceManager.GetString("Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet finished.
        /// </summary>
        public static string BetFinished {
            get {
                return ResourceManager.GetString("BetFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet is out of your limit.
        /// </summary>
        public static string BetIsOutOfYourLimit {
            get {
                return ResourceManager.GetString("BetIsOutOfYourLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet should be more that zero.
        /// </summary>
        public static string BetShouldBeMoreThanZero {
            get {
                return ResourceManager.GetString("BetShouldBeMoreThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet started.
        /// </summary>
        public static string BetStarted {
            get {
                return ResourceManager.GetString("BetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled by bookmaker.
        /// </summary>
        public static string CanceledByBookmaker {
            get {
                return ResourceManager.GetString("CanceledByBookmaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coefficient.
        /// </summary>
        public static string Coefficient {
            get {
                return ResourceManager.GetString("Coefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coefficient should be greater than 1.
        /// </summary>
        public static string CoefficientShouldBeGreaterThanOne {
            get {
                return ResourceManager.GetString("CoefficientShouldBeGreaterThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join to battle to make bets.
        /// </summary>
        public static string JoinToBattleToMakeBets {
            get {
                return ResourceManager.GetString("JoinToBattleToMakeBets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make bet.
        /// </summary>
        public static string MakeBet {
            get {
                return ResourceManager.GetString("MakeBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make bet on behalf of.
        /// </summary>
        public static string MakeBetOnBehalfOf {
            get {
                return ResourceManager.GetString("MakeBetOnBehalfOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me personally.
        /// </summary>
        public static string MePersonally {
            get {
                return ResourceManager.GetString("MePersonally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My bets.
        /// </summary>
        public static string MyBets {
            get {
                return ResourceManager.GetString("MyBets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to team.
        /// </summary>
        public static string OfTeam {
            get {
                return ResourceManager.GetString("OfTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private bet.
        /// </summary>
        public static string PrivateBet {
            get {
                return ResourceManager.GetString("PrivateBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded.
        /// </summary>
        public static string Succeeded {
            get {
                return ResourceManager.GetString("Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is too long.
        /// </summary>
        public static string TitleIsTooLong {
            get {
                return ResourceManager.GetString("TitleIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title should not be empty.
        /// </summary>
        public static string TitleShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("TitleShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url is incorrect.
        /// </summary>
        public static string UrlIsIncorrect {
            get {
                return ResourceManager.GetString("UrlIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made no bets in this battle.
        /// </summary>
        public static string YouHaveMadeNoBetsInThisBattle {
            get {
                return ResourceManager.GetString("YouHaveMadeNoBetsInThisBattle", resourceCulture);
            }
        }
    }
}
